declare module 'markdown-it-task-lists'
declare module 'markdown-it-footnote'
declare module 'markdown-it-toc-done-right'
declare module 'markdown-it-deflist'
declare module 'markdown-it-sub'
declare module 'markdown-it-sup'
declare module '@traptitech/markdown-it-katex'
