CREATE TABLE conflict_review (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    scope_id BIGINT NOT NULL,
    source_type VARCHAR(32) NOT NULL DEFAULT 'INGEST',
    source_execution_id BIGINT,
    from_page_id BIGINT NOT NULL,
    to_page_id BIGINT NOT NULL,
    from_page_title VARCHAR(255),
    to_page_title VARCHAR(255),
    conflict_type VARCHAR(64),
    strategy_key VARCHAR(64),
    strategy_label VARCHAR(128),
    route_reason VARCHAR(512),
    ruling_action VARCHAR(32),
    ruling_detail TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    decided_by BIGINT,
    decided_at DATETIME,
    executed_at DATETIME,
    execution_error TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_conflict_review_scope_status (scope_id, status),
    INDEX idx_conflict_review_execution (source_execution_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
