ALTER TABLE scope ADD COLUMN ingest_mode VARCHAR(16) NOT NULL DEFAULT 'review';
ALTER TABLE scope ADD COLUMN auto_suspended TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE scope ADD COLUMN auto_suspended_reason VARCHAR(512) NULL;
ALTER TABLE ingest_batch ADD COLUMN mode VARCHAR(16) NOT NULL DEFAULT 'review';
